# Generated by Django 5.1.2 on 2024-11-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='school_grade',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
