# Generated by Django 5.1.2 on 2024-11-13 00:45

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('level', models.CharField(max_length=20)),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
            ],
        ),
    ]
