# Generated by Django 5.1.2 on 2024-11-15 23:49

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_alter_module_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('banner', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Banner')),
                ('instructions', models.TextField(blank=True)),
                ('html_pt1', models.TextField(blank=True)),
                ('html_pt2', models.TextField(blank=True)),
                ('html_pt3', models.TextField(blank=True)),
            ],
        ),
    ]
