# Generated by Django 5.1.2 on 2024-11-17 02:05

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_alter_exercisetype_banner_sheet_sheetexercise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetexercise',
            name='dropdown_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='exercisetype',
            name='banner',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Banner'),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='sheetexercise',
            name='banner',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Banner'),
        ),
    ]
