# Generated by Django 5.1.2 on 2024-11-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_alter_sheetexerciseitem_content1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetexerciseitem',
            name='answer1',
            field=models.CharField(default='X', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sheetexerciseitem',
            name='answer2',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
