# Generated by Django 5.1.2 on 2024-11-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0007_sheetexerciseitem_answer1_sheetexerciseitem_answer2'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetexercise',
            name='title',
            field=models.CharField(default='X', max_length=50),
            preserve_default=False,
        ),
    ]
