# Generated by Django 5.1.2 on 2024-11-22 23:00

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0009_alter_sheetexerciseitem_content1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetexerciseitem',
            name='content1',
            field=django_ckeditor_5.fields.CKEditor5Field(default='None Required', verbose_name='Content 1'),
            preserve_default=False,
        ),
    ]
