# Generated by Django 5.1.2 on 2024-11-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0010_alter_sheetexerciseitem_content1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetexerciseitem',
            name='answer1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sheetexerciseitem',
            name='answer2',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
