# Generated by Django 5.1.2 on 2024-11-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_no', models.IntegerField(unique=True)),
                ('school_name', models.CharField(max_length=255)),
                ('school_type', models.CharField(max_length=30)),
                ('school_status', models.IntegerField()),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(max_length=255, null=True)),
                ('address_town', models.CharField(max_length=50)),
                ('address_state', models.CharField(max_length=20)),
                ('address_postcode', models.CharField(max_length=10)),
                ('postal_address_line_1', models.CharField(max_length=255, null=True)),
                ('postal_address_line_2', models.CharField(max_length=255, null=True)),
                ('postal_town', models.CharField(max_length=50, null=True)),
                ('postal_state', models.CharField(max_length=20, null=True)),
                ('postal_postcode', models.CharField(max_length=10, null=True)),
                ('full_phone_no', models.CharField(max_length=255)),
                ('lga_id', models.IntegerField()),
                ('lga_name', models.CharField(max_length=50)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
    ]
