# Generated by Django 5.1.2 on 2024-11-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_status',
            field=models.CharField(max_length=10),
        ),
    ]
