# Generated by Django 5.1.2 on 2024-11-03 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_systemcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
