# Generated by Django 5.1.2 on 2024-11-25 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0011_alter_sheetexerciseitem_answer1_and_more'),
        ('schools', '0007_school_email_school_phone_school_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_datetime', models.DateTimeField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_subscriptions', to='modules.module')),
                ('school_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_subscriptions', to='schools.schoolstudent')),
                ('school_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_subscriptions', to='schools.schoolteacher')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(auto_now_add=True)),
                ('end_datetime', models.DateTimeField(null=True)),
                ('completed', models.BooleanField(default=False)),
                ('score', models.IntegerField(null=True)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_sheets', to='modules.sheet')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_sheets', to='subscriptions.subscription')),
            ],
            options={
                'unique_together': {('subscription', 'sheet')},
            },
        ),
        migrations.CreateModel(
            name='SubscriptionExerciseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answer1', models.CharField(max_length=255)),
                ('answer1_correct', models.BooleanField(default=False)),
                ('student_answer2', models.CharField(max_length=255, null=True)),
                ('answer2_correct', models.BooleanField(default=False)),
                ('completed_datetime', models.DateTimeField(auto_now_add=True)),
                ('exercise_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='modules.sheetexerciseitem')),
                ('subscription_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='subscriptions.subscriptionsheet')),
            ],
            options={
                'unique_together': {('subscription_sheet', 'exercise_item')},
            },
        ),
    ]
