# Generated by Django 5.1.2 on 2024-11-25 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0011_alter_sheetexerciseitem_answer1_and_more'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionexerciseitem',
            name='completed_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionexerciseitem',
            name='exercise_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_items', to='modules.sheetexerciseitem'),
        ),
        migrations.CreateModel(
            name='SubscriptionExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(auto_now_add=True)),
                ('end_datetime', models.DateTimeField(null=True)),
                ('completed', models.BooleanField(default=False)),
                ('score', models.IntegerField(null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='modules.sheetexercise')),
                ('subscription_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='subscriptions.subscriptionsheet')),
            ],
            options={
                'unique_together': {('subscription_sheet', 'exercise')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionexerciseitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subscriptionexerciseitem',
            name='subscription_exercise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='subscriptions.subscriptionexercise'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionexerciseitem',
            unique_together={('subscription_exercise', 'exercise_item')},
        ),
        migrations.RemoveField(
            model_name='subscriptionexerciseitem',
            name='subscription_sheet',
        ),
    ]
