# Generated by Django 5.1.2 on 2024-11-26 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0011_alter_sheetexerciseitem_answer1_and_more'),
        ('schools', '0008_schoolstudent_school_teacher'),
        ('subscriptions', '0002_alter_subscriptionexerciseitem_completed_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='modules.module'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='school_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='schools.schoolstudent'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='school_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='schools.schoolteacher'),
        ),
    ]
