# Generated by Django 5.1.2 on 2024-11-26 04:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_subscription_module_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='school_teacher',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscription_datetime',
        ),
        migrations.AddField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 11, 26, 4, 23, 59, 363459)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriptionsheet',
            name='start_datetime',
            field=models.DateTimeField(),
        ),
    ]
