# Generated by Django 5.1.2 on 2024-11-26 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0011_alter_sheetexerciseitem_answer1_and_more'),
        ('schools', '0008_schoolstudent_school_teacher'),
        ('subscriptions', '0004_remove_subscription_school_teacher_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('school_student', 'module')},
        ),
    ]
