# Generated by Django 5.1.2 on 2024-11-27 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_alter_subscription_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionexercise',
            old_name='end_datetime',
            new_name='end_at',
        ),
        migrations.RenameField(
            model_name='subscriptionexercise',
            old_name='start_datetime',
            new_name='start_at',
        ),
        migrations.RenameField(
            model_name='subscriptionexerciseitem',
            old_name='completed_datetime',
            new_name='completed_at',
        ),
        migrations.RenameField(
            model_name='subscriptionsheet',
            old_name='end_datetime',
            new_name='end_at',
        ),
        migrations.RenameField(
            model_name='subscriptionsheet',
            old_name='start_datetime',
            new_name='start_at',
        ),
        migrations.AddField(
            model_name='subscription',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
    ]
