# Generated by Django 5.1.2 on 2024-11-04 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_alter_invitation_add_student_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='student_no',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
