# Generated by Django 5.1.2 on 2024-11-05 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_alter_invitation_student_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
