# Generated by Django 5.1.2 on 2024-11-06 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_delete_invitation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolstudent',
            old_name='date_ended',
            new_name='date_end',
        ),
        migrations.RenameField(
            model_name='schoolstudent',
            old_name='date_started',
            new_name='date_start',
        ),
        migrations.RenameField(
            model_name='schoolteacher',
            old_name='date_ended',
            new_name='date_end',
        ),
        migrations.RenameField(
            model_name='schoolteacher',
            old_name='date_started',
            new_name='date_start',
        ),
    ]
