# Generated by Django 5.1.2 on 2024-11-07 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_rename_date_ended_schoolstudent_date_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolstudent',
            old_name='grade_level',
            new_name='school_grade',
        ),
    ]
