# Generated by Django 5.1.2 on 2024-11-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_rename_grade_level_schoolstudent_school_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
