# Generated by Django 5.1.2 on 2024-11-26 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_school_email_school_phone_school_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolstudent',
            name='school_teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teaches', to='schools.schoolteacher'),
            preserve_default=False,
        ),
    ]
